package main

import (
	"errors"
	"fmt"
	"math"
	"net/http"
	"strconv"
	"time"

	"github.com/garyburd/redigo/redis"
	"github.com/gin-gonic/gin"
)

var (
	// generated by command line `head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo ''` on Linux bash
	testAPIKey  = "yb2Q1ozScRfJJ"
	adminAPIKey = "z77BV0FABp2PU"
)

func checkInput(c *gin.Context) (u string, err error) {
	if !localMode {
		apiKey := c.PostForm("apikey")
		if apiKey == "" {
			c.JSON(http.StatusOK, gin.H{
				"Status": "error",
				"Result": "missing api key",
			})
			return "", errors.New("missing api key")
		}

		accountKey := fmt.Sprintf("imchenwen:account:%s", apiKey)
		acc, err := rd.Get(accountKey)
		if err != nil || acc == nil {
			if apiKey == testAPIKey {
				rd.Put(accountKey, 60)
				acc, _ = rd.Get(accountKey)
			} else if apiKey == adminAPIKey {
				rd.Put(accountKey, math.MaxInt32)
				acc, _ = rd.Get(accountKey)
			} else {
				c.JSON(http.StatusOK, gin.H{
					"Status": "error",
					"Result": "incorrect api key",
				})
				return "", errors.New("incorrect api key")
			}
		}
		rateLimitQuote, err := redis.Int(acc, err)
		if err != nil {
			c.JSON(http.StatusOK, gin.H{
				"Status": "error",
				"Result": err,
			})
			return "", err
		}

		rateLimitKey := fmt.Sprintf("imchenwen:ratelimit:%d", time.Now().Unix()/60)
		rateLimitValue, err := rd.Get(rateLimitKey)
		if err != nil || rateLimitValue == nil {
			rd.PutWithTimeout(rateLimitKey, 1, 60)
		} else {
			rateLimit, err := redis.Int(rateLimitValue, err)
			if err != nil {
				c.JSON(http.StatusOK, gin.H{
					"Status": "error",
					"Result": err,
				})
				return "", err
			}
			if rateLimit > rateLimitQuote {
				c.JSON(http.StatusOK, gin.H{
					"Status": "error",
					"Result": "exceeded rate limit",
				})
				return "", errors.New("exceeded rate limit")
			}
			rd.Incr(rateLimitKey)
		}
	}
	u = c.PostForm("url")
	if u == "" {
		c.JSON(http.StatusOK, gin.H{
			"Status": "error",
			"Result": "missing url",
		})
		return "", errors.New("missing url")
	}
	return
}

func handleAddUser(c *gin.Context) {
	apiKey := c.Param("apikey")
	if apiKey == "" {
		c.JSON(http.StatusOK, gin.H{
			"Status": "error",
			"Result": "missing api key",
		})
		return
	}
	quote := c.Param("quote")
	quoteValue, err := strconv.Atoi(quote)
	if err != nil {
		c.JSON(http.StatusOK, gin.H{
			"Status": "error",
			"Result": err,
		})
		return
	}
	accountKey := fmt.Sprintf("imchenwen:account:%s", apiKey)
	rd.Put(accountKey, quoteValue)
	c.JSON(http.StatusOK, gin.H{
		"Status": "OK",
		"Result": fmt.Sprintf("created API key %s with quote %d", apiKey, quoteValue),
	})
}

func handleDeleteUser(c *gin.Context) {
	apiKey := c.Param("apikey")
	if apiKey == "" {
		c.JSON(http.StatusOK, gin.H{
			"Status": "error",
			"Result": "missing api key",
		})
		return
	}
	accountKey := fmt.Sprintf("imchenwen:account:%s", apiKey)
	rd.Delete(accountKey)
	c.JSON(http.StatusOK, gin.H{
		"Status": "OK",
		"Result": fmt.Sprintf("deleted API key %s", apiKey),
	})
}
